export const FETCH_CENTERS_SUCCESS = 'FETCH_CENTERS_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_LOADING = 'AUTH_LOADING';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
