export const FETCH_CENTERS_SUCCESS = 'FETCH_CENTERS_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';